### ISSUE TITLE
Heartbeat?

### ISSUE THREAD

**Issue by ituri** [bugfx/ESP32-sprinkler-controller#1]
Hi bugfx,

I'm trying to adapt your sketch to my own needs and I currently have the problem that my valves turn off after 15 minutes. I assume that this has to do with the heartbeat. From reading your code I can't really figure out how this is supposed to work. 
Do you generate a topic on your mqtt broker every couple of minutes that serves as a heartbeat? If yes, how?

I'm using mosquitto and I have `$SYS/broker/uptime` as a topic that gets updated quite frequently. However, using that as a heartbeat topic (`const String heartbeat = "$SYS/broker/uptime";`) didn't help and my valves still turn off after 15 minutes.

I'd be very happy if you could help me.

**Comment by bugfx** [comment]
Hey ituri,

you are right it's the heartbeat.

In case your ESP32 has a good wifi connection and you are not experiencing problems over longer time periods you should be fine disabling the heartbeat in the mail loop.
`//mqttcheckHeartbeat();`

The ESP32 on its own should be able to reconnect in case of wifi problems. In my case every 2 or 3 weeks the ESP lost its connection, got freezed and had to be restarted manually.
To avoid that valves stay open in this case I inserted the mqttcheckHeartbeat function.
Since then I noticed no problems anymore.

The heartbeat is updated every minute by my openHAB Server, with acts as an mqtt-client in my setup.
Openhab -> mosquitto Server -> ESP32 ....

**Checking the code again I found the problem.** 
I'm really sorry, but I never used the "const String heartbeat" and instead used a different hardcoded string while checking the mqttIncommingTopic:

```
//was the last incoming mqtt topic an heartbeat from the server
    if (mqttIncommingTopic == "SYS000AE01SW01") {
```
Change this to:
```
//was the last incoming mqtt topic an heartbeat from the server
    if (mqttIncommingTopic == heartbeat) {
```

I'will fix this soon, but need to test the hole sketch this first.
You should be fine making this change.

Big THX.
bugfx

**Comment by ituri** [comment]
Thanks, I've incorporated your fix already. I will test it tonight.

BTW, if you want to talk a look: https://github.com/ituri/ESP32-sprinkler
I took your code and added an esp-dashboard to it so that one can also control the valves via a fancy website running on the ESP.

**Comment by bugfx** [comment]
Nice, I did not have time to run it by my self, but I will definitely do this in the next weeks.

I tested the fix and the new connection management this week and had no issues.
The connection management should work better in poor signal scenarios.
